site_name: CakePHP 3 Bootstrap Helpers

site_url: https://holt59.github.io/cakephp3-bootstrap-helpers
repo_url: https://github.com/Holt59/cakephp3-bootstrap-helpers

pages:
    - Getting Started: index.md
    - Form Helper:
        - Basic usage: form-helper/basics.md
        - Horizontal forms: form-helper/horizontal.md
        - Custom file inputs: form-helper/custom-file-inputs.md
        - Buttons, Groups & Toolbars: form-helper/buttons-et-al.md
        - New input options: form-helper/new-input-options.md
    - Html Helper:
        - Creating icons: html-helper/icons.md
        - Labels & Badges: html-helper/labels-badges.md
        - Alerts: html-helper/alerts.md
        - getCrumbList: html-helper/getcrumblist.md
    - Modal Helper:
        - Basic usage: modal-helper/basics.md
        - Without HTML: modal-helper/no-html.md
        - Fully customized modals: modal-helper/custom.md
    - Navbar Helper:
        - Basic usage: navbar-helper/basics.md
        - Automatic "active" link: navbar-helper/auto-active-link.md
    - Panel Helper:
        - Basic usage: panel-helper/basics.md
        - Panel groups: panel-helper/groups.md
    - FAQ: faq.md

markdown_extensions:
    - "mkexts.tabs:TabsExtension"
    - "mkexts.prism:PrismCodeExtension"

theme: null
theme_dir: bootstrap-theme
